# Time constants (in seconds)
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86_400

# Status code ranges
STATUS_CODE_SUCCESS_MIN = 200
STATUS_CODE_SUCCESS_MAX = 300
STATUS_CODE_CLIENT_ERROR_MIN = 400
STATUS_CODE_CLIENT_ERROR_MAX = 500
STATUS_CODE_SERVER_ERROR_MIN = 500
STATUS_CODE_SERVER_ERROR_MAX = 520